import type {ProjectSummary} from "../types";

// تولید دادهٔ mock برای توسعه محلی و تست کامپوننت‌ها
// حاوی ترکیبی از پروژه‌های فعال، تکمیل‌شده، معلق و آرشیو شده است
export const createMockProjects = (): ProjectSummary[] => {
  const now = new Date();
  return [
    {
      id: "prj-201",
      name: "Marketing Website Redesign",
      description: "Refresh the market-facing website with a cleaner funnel and stronger experiment tracking.",
      status: "active",
      progress: 65,
      members: 5,
      deadline: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 12),
      budget: 18000,
      startDate: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 18),
      dueDate: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 14),
      updatedAt: new Date(now.getTime() - 1000 * 60 * 25),
      teamId: "tm-101",
      coverColor: "from-violet-500 via-indigo-500 to-blue-500",
      teamMembers: [
        {id: "tm-101", name: "Behzad Piray", role: "Owner", avatarColor: "from-violet-500 to-indigo-500"},
        {id: "tm-102", name: "Ava Collins", role: "Admin", avatarColor: "from-sky-500 to-cyan-500"},
        {id: "tm-103", name: "Noah Kim", role: "Member", avatarColor: "from-emerald-500 to-teal-500"},
      ],
      tasks: [
        {id: "tsk-1", title: "Landing page copy refresh", assignee: "Ava", status: "in_progress", dueDate: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 2)},
        {id: "tsk-2", title: "A/B test funnel setup", assignee: "Behzad", status: "todo", dueDate: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 5)},
        {id: "tsk-3", title: "Performance audit", assignee: "Noah", status: "done", dueDate: new Date(now.getTime() - 1000 * 60 * 60 * 12)},
      ],
    },
    {
      id: "prj-202",
      name: "Mobile App Launch",
      description: "Launch the first mobile release with QA sign-off and marketing readiness checks.",
      status: "completed",
      progress: 100,
      members: 4,
      deadline: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 3),
      budget: 24000,
      startDate: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 40),
      dueDate: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2),
      updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 6),
      teamId: "tm-102",
      coverColor: "from-sky-500 via-cyan-500 to-teal-500",
      teamMembers: [
        {id: "tm-102", name: "Ava Collins", role: "Admin", avatarColor: "from-sky-500 to-cyan-500"},
        {id: "tm-104", name: "Mila Garcia", role: "Member", avatarColor: "from-amber-500 to-orange-500"},
      ],
      tasks: [
        {id: "tsk-4", title: "App store assets", assignee: "Mila", status: "done"},
        {id: "tsk-5", title: "Release checklist", assignee: "Ava", status: "done"},
      ],
    },
    {
      id: "prj-203",
      name: "CRM Integration",
      description: "Align sales and support workflows by integrating the CRM with the customer lifecycle engine.",
      status: "on_hold",
      progress: 38,
      members: 3,
      deadline: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 21),
      budget: 12000,
      startDate: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 10),
      dueDate: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 23),
      updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 12),
      teamId: "tm-103",
      coverColor: "from-amber-500 via-orange-500 to-rose-500",
      teamMembers: [
        {id: "tm-103", name: "Noah Kim", role: "Member", avatarColor: "from-emerald-500 to-teal-500"},
        {id: "tm-106", name: "Sara Nouri", role: "Admin", avatarColor: "from-pink-500 to-rose-500"},
      ],
      tasks: [
        {id: "tsk-6", title: "Field mapping", assignee: "Noah", status: "in_progress"},
        {id: "tsk-7", title: "Integration QA", assignee: "Sara", status: "todo"},
      ],
    },
    {
      id: "prj-204",
      name: "Customer Feedback Loop",
      description: "Capture product feedback in a structured loop between support, design, and product teams.",
      status: "active",
      progress: 47,
      members: 6,
      deadline: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 5),
      budget: 9600,
      startDate: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 9),
      dueDate: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 8),
      updatedAt: new Date(now.getTime() - 1000 * 60 * 10),
      teamId: "tm-104",
      coverColor: "from-emerald-500 via-teal-500 to-cyan-500",
      teamMembers: [
        {id: "tm-104", name: "Mila Garcia", role: "Member", avatarColor: "from-amber-500 to-orange-500"},
        {id: "tm-105", name: "Leo Martin", role: "Viewer", avatarColor: "from-stone-500 to-slate-500"},
      ],
      tasks: [
        {id: "tsk-8", title: "Feedback tagging", assignee: "Mila", status: "in_progress"},
        {id: "tsk-9", title: "Support dashboard", assignee: "Leo", status: "todo"},
      ],
    },
    {
      id: "prj-205",
      name: "Security Audit",
      description: "Complete security and compliance review for infrastructure, auth, and platform resilience.",
      status: "archived",
      progress: 100,
      members: 3,
      deadline: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 30),
      budget: 7000,
      startDate: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 50),
      dueDate: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 28),
      updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 48),
      teamId: "tm-105",
      coverColor: "from-slate-600 via-zinc-500 to-stone-500",
      teamMembers: [
        {id: "tm-105", name: "Leo Martin", role: "Viewer", avatarColor: "from-stone-500 to-slate-500"},
      ],
      tasks: [
        {id: "tsk-10", title: "Review report", assignee: "Leo", status: "done"},
      ],
    },
    {
      id: "prj-206",
      name: "Performance Optimization",
      description: "Improve the application response time and reduce operating cost across the platform core.",
      status: "active",
      progress: 82,
      members: 2,
      deadline: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 9),
      budget: 15000,
      startDate: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 22),
      dueDate: new Date(now.getTime() + 1000 * 60 * 60 * 24 * 11),
      updatedAt: new Date(now.getTime() - 1000 * 60 * 20),
      teamId: "tm-106",
      coverColor: "from-pink-500 via-rose-500 to-orange-500",
      teamMembers: [
        {id: "tm-106", name: "Sara Nouri", role: "Admin", avatarColor: "from-pink-500 to-rose-500"},
        {id: "tm-101", name: "Behzad Piray", role: "Owner", avatarColor: "from-violet-500 to-indigo-500"},
      ],
      tasks: [
        {id: "tsk-11", title: "Monitoring dashboard", assignee: "Sara", status: "in_progress"},
        {id: "tsk-12", title: "Cache tuning", assignee: "Behzad", status: "done"},
      ],
    },
  ];
};
